[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.111.3"

[headers]
  [[headers]]
  for = "/*.css"
    [headers.values]
    Content-Encoding = "identity"

